# COPYRIGHT Dassault Systemes 2007
#======================================================================
# Imakefile for module PLMBRTST_SetupDataFinder.m
#======================================================================
#
#  Jan 2007  Creation: Code generated by the CAA wizard  HCG
#======================================================================
#
# LOAD MODULE 
#
BUILT_OBJECT_TYPE=LOAD MODULE 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES) \
			CatXmlItfBase NS0S3STR CatXmlItfExt \
			JS0ERROR CATPLMIdentificationAccess \
                        KnowledgeItf \                        
			CATPLMComponentInterfaces \
			PLMSetupDataInterfaces 

# System dependant variables
#  PLMLibraryNavUseItf PLMLibraryNavUseImpl \                        
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
